hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "a2bbcf538477125e1241c5f617fa1b72d0d8d88f48b893fe6c1557829dfe7c92"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "1562c21781759f538378d67275bac4497dd15b68b85d13e9c5b613a1ba46cacc"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "35058f2b4e05ff3b459d130620b8c4ee78275fb06ff96d5b6319fe8705ed3e68"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b72d00d529ec694ae354b73f6b36d4ec2b830c60c05cc31f46d00ac7ddf8a26b"
metafile = true

[[files]]
file = "mods/better-block-entities.pw.toml"
hash = "7b587cd143d5f24804b6f20c6adb51816afd1f8167ab15f434d8b19ad725b7c6"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "a8f073ab0640d9e501fe3fc95d282306000fd6eab3186fd682269c0d0913b307"
metafile = true

[[files]]
file = "mods/capture-playback.pw.toml"
hash = "56d804cb1b2716b5f672b50d7df1087deb42eaefaa3dfc765c6fd5fea8e5a2b6"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "764aea7b3c8d48de1c290c22193c7ecdea379b1b683f10d9ab6bfe0eb4658e06"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "fbb61854650a7cdf7eb2244e0599bae2f0541864a9b7cf74f8272972e6bdb18e"
metafile = true

[[files]]
file = "mods/chunk-debug.pw.toml"
hash = "22d7379333094a1134d11b215f8488bc4ca1dacf577c9e6e4b5ff7636831b0d3"
metafile = true

[[files]]
file = "mods/clear-despawn-reworked.pw.toml"
hash = "fa815918bfabc29fef2a4c67b61c1b0a37885600f00117376fdf36c59bb10da4"
metafile = true

[[files]]
file = "mods/client-commands.pw.toml"
hash = "3cdf20fd9407965a151e78de03d7d8c821b2d814a144b1882870577ec1f54b64"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "cf240cf1adafaeb2c2b1490d7cba135c8befab720bf43473e7c4240c424d221b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d53b229a5588d33a8dac8682cba4371b22b2cbe2541c7129506cfbd44daaf6f8"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "9071b0f2487ec9054e68ac0a4d10aa0331b7fd60ab6015d958c7a58ad9ae44ec"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "c23a1be7641341478b09c5c4f835b5e024a246f9e8521e92905bcab0d0e8cce0"
metafile = true

[[files]]
file = "mods/essentialaddons.pw.toml"
hash = "9a9e48987f07bed76b1bc4d791d1d712694d4a7ea0ad7826abc29120390746d3"
metafile = true

[[files]]
file = "mods/essentialclient.pw.toml"
hash = "15973de16d7ea7d85898116a0305f0e72fb810b802d01c430af9e31635a969e7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "241cece83d6a3c7c0338a9b625972ee25747d14684810778bc64d9613f7a49a1"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "d6250f89ac5f0ac6ea08f1345d083c1fa5cbda12670ba016e1457ec6f6a8ce32"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "6839f53544009603fefc7f72b4f724bf1cbbe0d8d6c0a0f27bf53503655b5345"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "816b735b2ad505476201800a99f527e61b392b712b9d20ca9edcce05f412fe87"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "b748f3c5782acd14bc088ab235b949bd3237a246c7221e06b7bc25d9310daa73"
metafile = true

[[files]]
file = "mods/g4mespeed.pw.toml"
hash = "8a0609516ec248ee62ed1b7d5d514a24d454741a16f3a52b61af95d15ed39620"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "9e7bacd24307639764f3b74ae35a562b6becf2701637b816de0eaae15ab714c0"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "c4b8bff059280b88e4472816f3e4834cf6a556d0cc111288adf9521a43785018"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "7b7999342af9d5555dc3851b23e9e45948fd6df25fea8113da4e680cb404383c"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "8643786cd883f7686a11f2bcc773acbe6559a7d3d13af3ed690e8d7fa58ef343"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "38bf2b56bbd2cbb9cc4e3ac9e9ecdf415ff1152ff1bfd68d0843ed58d7a6ba02"
metafile = true

[[files]]
file = "mods/litematica-server-paster.pw.toml"
hash = "a2424e61047a5b254eb49e63fdc1972a1202ec1135bcd8ea85d671ab7caf0f9b"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "61e1149d5642bb6bd3d2c718054107fa7a6f1b1044f5573d5ecbab3b94f9e281"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/malibind.pw.toml"
hash = "1187b51169e8e83ef82c0036ba964003d55a48f06355f28283b2ad1f5b179ff5"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "6324b634d5e464cf2606cce4e1d9b923701cad31764858d982fe0738129e0e4e"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "6d26fbac2dca7845d5de9e5fbbe3dbcb7541ccb952e4f5f14a92e618d5448965"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "b261880bd245c83c51b729199452da12b0766a4aa0210fc79d0c48161cbfcc49"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "67116d1cf5d38dfd27aded9d675afcc625d720a4d457660ff82db760934d9f4d"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "51ff93e279e03cb3cd77a5be0df777cdcd975d35b5149180d9dc724e47168c76"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "0544fefc6f04f2b408b2c6b4dd3e4bf7d0a4048f1fad6ddf63357549d7446165"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "a60ccef90c959893aa4609f93ffbced0c77e92cb6e63e71c502f00e0056b9919"
metafile = true

[[files]]
file = "mods/nbt-copy.pw.toml"
hash = "aa3e2a5123eab3a0fbab1c3eca9b46b6130665cbcbac379c7df1eef5c1f2b6d6"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "31188934bcb30e1c88efe708b3ffdb7b9ae34595815c909fceb244fbab31cb88"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "9e0266e282a6b5f52ea5208ba88cdf8ac71ac0d13b23f4f92b6e8ec15c1ecc16"
metafile = true

[[files]]
file = "mods/packed-packs.pw.toml"
hash = "551cbb16245a12123b6c4ece789012b31a133d50ad3024ec4b9db7d13094d0e5"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "c5cf55b4ec0c694443ae7769d9d96b7ae69aef8a94e7d74f884014b7f5102234"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "5f252eb4e95f3028398a7148bcfd8dfaeeeb69d573c5ab34c2cdf54f2a29478b"
metafile = true

[[files]]
file = "mods/redstone-multimeter.pw.toml"
hash = "3d9d6b0c0723f6b12cd2e723288f37ba12856da85230963d5e9bea3f1ca5edc3"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "565c943b5006c36137a2fe55e4b8433e134c3d1011a37c5f5124cee67b671cb8"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "f10b01f1c112138bd2cae598b8e5b3e8511b6c47155276002a8e4319c9b87a4e"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "f61627c24489f95e3458ecf3f74bdd5aac697e2bce1f62afeaa79f28a17e13c5"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "986e43ff06d2a79effec6e219aca063d7b53a98096c5f63983f23cf54c11c7e5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9d340481c374a20067d1748c1a4991626bce9d7812f0bdb96072cd7a15d35462"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "cbe31523a511324897f507f664305b7696e5f682609f42a8c08effda13bdf889"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c073f13897a838e3c409e46b8a1d8cb510d6a6584dd815aeadaf4886f1779513"
metafile = true

[[files]]
file = "mods/suggestion-tweaker.pw.toml"
hash = "9a1695184cdb4646ae5deef3ed576e7dc1235cff1ff20493aa482a2c512928b0"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "39a3a1247761a61f8e108b31284d748f1a1324d4c7ba87b2e768351b0f8a0e74"
metafile = true

[[files]]
file = "mods/techutils.pw.toml"
hash = "f321380b12096a6b4ee3ec6845acebe7acb51bca8ea69302053b112e2e362eaa"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "060b425b0055d87f793f7f8325aa8ad637cb84dd4b33a2908646372e201d5f9b"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "4e83c1af9a9c49d4ca7a67adc6370bcf58fabfa040ace15a62e6e96cdb3064b5"
metafile = true

[[files]]
file = "mods/unobtainable-blocks.pw.toml"
hash = "e620c847af24c12c8fa9eeff26f2be1b8e5a5e027ff7140efd2d4f73ddc258b4"
metafile = true

[[files]]
file = "mods/viabackwards.pw.toml"
hash = "9b04f2984f485fa081ce181944e87dea3015cdfeb6b8813ff68823525d3b553f"
metafile = true

[[files]]
file = "mods/viafabric.pw.toml"
hash = "695d8765874f311d578b9336753d9e4c9c2ce9df927a517614f234237fcd7e7a"
metafile = true

[[files]]
file = "mods/vkm.pw.toml"
hash = "f038f18dde1d1163e239c3eb8ecc981f08ce3aff929952134b84ab5397e4f839"
metafile = true

[[files]]
file = "mods/voxy.pw.toml"
hash = "5a32a818f9c756a56536b56298d1a95c81cf04fbf8f836db2655d4b3f3322d06"
metafile = true

[[files]]
file = "mods/wikirenderer.pw.toml"
hash = "4f1aa777033c2c634fe97f7d90561468e75bf5af47123d392939545267d1563b"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "8aea9229ab3b30b7c066b226de6b38585449467843aeb0cdc6a7f62d1a3dc1db"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "52e2529d56443d8efab4a753fdb935b0b08d775b9fdebaa42a7c8063d617dbe1"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1113d43c39a9866252a83ee50d16aa3ce6fcf749acd84d58b05ca09eba4d187b"
metafile = true

[[files]]
file = "resourcepacks/redstone-tweaks.pw.toml"
hash = "31b53c71c2bf08da156167befe54b5717e71ee871e10ef78a70967a0bdc8b56b"
metafile = true
