name = "RedstoneTools"
author = "Scorpio"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "626da144c86d495f6c3dc3067a96f0f2b625d5eea73752b8bc310325017e58c6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
