name = "RedstoneTools"
author = "Scorpio"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f7ea8eb002bb8fdbd1e10678c0d974db686b8c466847b4001dbeda4a99a5705"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
