name = "RedstoneTools"
author = "Scorpio"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d90a7c5f4c13bd6613a01cb664e556bd6e77df443c42fbf170aeb24f6f71b243"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
