hash-format = "sha256"

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "00ef45b83509a2dd01fc672c69e698c42a8fd99b15cc15ef3ff3509b6ac402d1"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "a91b9fecfbd788861792429ca7c36c0492503b8000554cb87f89546bc884406a"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "f620ff71fdf9c6116830e397e2e0af5106d8e409b9227e8dde0b46ad60f394b8"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "4fa894a9e834a987e68bb2f3dac003ebc72c104c37046c43f2e55bf4e4b3bd10"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "fb605ec9729252c00fe598d1e6ecbbcbb94dd7021c2aa3378bcca3e6de49c002"
metafile = true

[[files]]
file = "mods/zfastnoise.pw.toml"
hash = "4a5c29c77decfb7ed5d57f2b2fa062837218f6221cc96d8b9484e83dd6be5144"
metafile = true
