name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4341b0fcb1a6fa8b2be920e33e32ab75f21cad1e4917820f60e0f6c24ed70058"

[versions]
fabric = "0.18.4"
minecraft = "26.1-snapshot-7"

[options]
acceptable-game-versions = ["26.1-snapshot-4", "26.1-snapshot-5", "26.1-snapshot-6"]
