name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e0f2148b4831847a102943c7854f65ef4786835090e04c7c38a53219fc63362"

[versions]
fabric = "0.18.4"
minecraft = "26.1-snapshot-8"

[options]
acceptable-game-versions = ["26.1-snapshot-4", "26.1-snapshot-5", "26.1-snapshot-6", "26.1-snapshot-7"]
