name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc46b74f933146cfa9b943d24795ca997b0a4e6fe00eaacca0003e86428488c6"

[versions]
fabric = "0.18.4"
minecraft = "26.1-snapshot-7"

[options]
acceptable-game-versions = ["26.1-snapshot-4", "26.1-snapshot-5", "26.1-snapshot-6"]
