name = "RedstoneTools"
author = "Scorpio"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fac35d954c2a855c5a1c833cbe485bd1bfa6dbe87b079398a685f785aee3b147"

[versions]
fabric = "0.18.4"
minecraft = "1.20.6"
