name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc9e85c508dc20ab9fd22953de6f89f2112db6556bc4cb92f25d0ba7a7da161e"

[versions]
fabric = "0.18.4"
minecraft = "1.20.6"
