name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fe949e2c6e23c1326a66a342bf0ec352204a8cccf56c93393d9d57cd0b4bcf6"

[versions]
fabric = "0.18.4"
minecraft = "1.16.5"
