name = "RedstoneTools"
author = "Scorpio"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0271cd7e33c0a77851ae6d09d34f10a34d9eb379f9ba4d8aa55a3801308d66e8"

[versions]
fabric = "0.18.4"
minecraft = "1.18.2"
