name = "RedstoneTools"
author = "Scorpio"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45a4379a1a5695175bff12381e0b6f5506009200950dc9167717f1a242768200"

[versions]
fabric = "0.18.4"
minecraft = "1.18.2"
