name = "RedstoneTools"
author = "Scorpio"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caf33c2a93231151d73afd2ed1b9c6d7fc5cf649c337b5d7a79a7127439b246a"

[versions]
fabric = "0.18.4"
minecraft = "1.19.4"
