name = "RedstoneTools"
author = "Scorpio"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fba8d1549636c99128b9ce23f2caa5c518b197ff5dbe2ec6b5b6076ac3cdd9a2"

[versions]
fabric = "0.18.4"
minecraft = "1.19.4"
