name = "RedstoneTools"
author = "Scorpio"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e3d8818482c26028e0410650d6bf374d688d03f535981f7b5d1c1b3ba5008df"

[versions]
fabric = "0.18.4"
minecraft = "1.19.4"
