hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "db11f140935d318030ec2663bcea0bf241dc65b84ca6e3340fd6e60bbdaf904b"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "9f12ada529ac9c05c4307aadadb39b9de12c213e51c600421bc0bcdcb73761b0"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "b4eedfc0c15e28fc4984f406e3bf69b2453815f5c7ac2768a40518575464320a"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "cea71ad36ac75bfd1c23bd2f0d6ec4cc84c857b8483a122eabe051492c775586"
metafile = true

[[files]]
file = "mods/better-block-entities.pw.toml"
hash = "0cd41edda7541ac376fcdf911aa7dfc7dec3448505b6c24059836fd6c284c3e0"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "7a057e2816d48fe0626f8f1586c6c490d44f39ce6f3f1d62aace7dc27a714489"
metafile = true

[[files]]
file = "mods/capture-playback.pw.toml"
hash = "48260095521a5b8b134106850b18071389b702eddcef97558b8c37dbaa321658"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
hash = "fdf372be718024b32de46e0a9e472bfde8a405dad18ea7fe04530cc3de04a4ee"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "0b8205fd54ac83c4926425a9efca135e44e4813e45a4779a1af28e51378851e4"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "3d21a4a42390d815afb6fe6f1bc13a07a1b2685204d09786d6acc92d760d9429"
metafile = true

[[files]]
file = "mods/chunk-debug.pw.toml"
hash = "7c6498f598f7a71d7d285b87ab44383e3be1eed32330aaa7d0e4ff5332256346"
metafile = true

[[files]]
file = "mods/clear-despawn-reworked.pw.toml"
hash = "c673b7655e6a7b7a774ca1a16a5628b0862c29dbad494e04776693e8a1505fdb"
metafile = true

[[files]]
file = "mods/client-commands.pw.toml"
hash = "a702f9ea1f18c204a8dfa0729b6c096f046befac367a87a5e2737db5a936feed"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a216e613b5ada8a83972394c8b52331388f6d3e41187a04c3bced3f1752bea70"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "be5ad8c42f54f77c573dc4cdb05b58243304ca2179f802dafc7030d9809a4072"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "a86751e4931b83d8f3de8e84e38f2dc0aa316e40c99b9e9f03a9276659a474b6"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "095e001e62f6ed7b4781232a40c8689385034b31d2ec363c7fc657dfe46f455a"
metafile = true

[[files]]
file = "mods/dcwa.pw.toml"
hash = "c7aa2123dc093558b6830e3b126e8fb9237eb8ddaa0d8b6bddd125f4ee3e2999"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "dff937930734d00e3cd2c644d20d5015df3ad53cc9d23fae2704326774cadbad"
metafile = true

[[files]]
file = "mods/essentialaddons.pw.toml"
hash = "85ab26c8f5828b8791573d5531c26aa974bd108b922063c28620d8dffa0b946f"
metafile = true

[[files]]
file = "mods/essentialclient.pw.toml"
hash = "8aafbc8d1160656fa6933a652d84fb0f05412fc2fe364da22555efef06d21b76"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "256b3418c1af70c2ae837937a7d53f007cb12eb81eec57afbc03e33cdb43cef6"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "0193bffdfefb49399085f488f41a0d7b52de061726647b99669b4a141a7d44a1"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "6b8172ae5535340b23cbf3978645d6d8374c3b0f8b43d999a559f7dd9ac019e6"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "58d01821618f01d70700ef0918a3e698cdc874926183e59be420df2021493b1c"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "d92eb3e33f1ecd978c9c8e3840a5aefdab97d3c56301fdd3f1cd8f986dc1bf93"
metafile = true

[[files]]
file = "mods/g4mespeed.pw.toml"
hash = "c6327eb21fc29487f7dc3c96b6f7467694d81c1b9f40ddfab8d73b40add8d95b"
metafile = true

[[files]]
file = "mods/hold-that-chunk-v2.pw.toml"
hash = "1918892fecd685c816b464cd11acc587be07e70a9d7ae57223cdfea8cd84e844"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "49bfa364f9e46b6a53f6dde155fdd3e498178de20220f17fb5f67faea45376b0"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "70241e5d38f2d3382aa4bc846f480fa9df9cca82eeffc5ce483bfa298ea517fd"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c63c8fe4489436e9a213c95dfbed7f9905ab7d1c4143752795d37f661ad495e0"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "2f2b80dff82bf3e8a14e6d295ddc5b53c98ad498a30f1fafd2e221d9302edf24"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "53393c4504919a7867dc8550e2f7dbbf71bcb627c8ab742ad771ebb65273cd16"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "e26dacab5ed497b7bf6500e389eba5e21cd4b9d7b38089045cd26818a4d2f589"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "49768af6ea6589c8b96ee1224f2a25e9c60bc608fd696cc6a1eb38bf54f6c5ed"
metafile = true

[[files]]
file = "mods/litematica-server-paster.pw.toml"
hash = "6b0fa58d1854b19dadda02473b871c735d06feb7c9cb5b73a389d004b1f4c8d4"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "fee996b1be4d393a7e5c5d94404a6d8475fc4940aea318b122dea4d9500719b1"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "11b5a9241c028f5e3cf9befd6975ec80cff1497a7dd23dde17c0f74e9a7b7a52"
metafile = true

[[files]]
file = "mods/malibind.pw.toml"
hash = "ad50cda4f719dc342b79a30a0efa16a5fd4629fbc9c5b3c9df8b0f918675443a"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "b84cd432bfa63d97601bf6347aecb3395ba8aa6e81c0ec049a8852276b5d131a"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "cb1d91e44f9495df2d2d701bae261e08f0b9d9afd7a65fa1ad5fc05a8849c1c4"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "14800fc12fd4b92497c0f26455523783bdf59194233bdaa71d4864b3d436929a"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "7d9030886363f59a082873ba8aa81a2a6f6e699cd02f1fc42679a6bc3a416357"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e92d199e6d874cf21bbff4c1f6cf6709129927d925be8f62be7514e6317396ca"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "d122f53efcfd54e24ef7e15247bbebe788d4ea475c2f5b84ccc1254dc625a1ec"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "ce6b7de3b16555ecc50526e569b81da09b5b4cdc6c2e21ccc69eb685f3e3b74d"
metafile = true

[[files]]
file = "mods/nbt-copy.pw.toml"
hash = "aa3e2a5123eab3a0fbab1c3eca9b46b6130665cbcbac379c7df1eef5c1f2b6d6"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7bee42e6773e9bd8bc6d6fd85a63a61ad0871224c3a8e31de0d0090944d60617"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "54dd8b88e92786d96c2487b7d6a473fbb7cd4576cec3a543788cfab327ffd623"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "97577102ea2a77ad1262e691485a36106092788ec882b6faf5d4c28ad9675afc"
metafile = true

[[files]]
file = "mods/packed-packs.pw.toml"
hash = "e0097ab5153ee3ee86b1f2fb0b4b729bd670dbd6382912a3e2a02fbac7ed3513"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "84cb0dcad9ac46d22adba4fb7924951affa6ac5e46027a3b25fa9a0db8d91b2b"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "c35b01442e935507d657699d75017ed8c939de67d65a38cf1ae4926e9d56762e"
metafile = true

[[files]]
file = "mods/redstone-multimeter.pw.toml"
hash = "c05d43ada68ab67443e0c25fb65292090bc342e6ebe73974a6cdb0fb3084e680"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "88f9a71bf06f4959b220abab8542e4763747903e9e5ef150c38ae79c83870077"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "c683a93d5c474b45c4a9c50510daf2355a29b0e9f91fb14483e5677ea0a925cb"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "6393fb152e8a7f073dbb630145e8dc44215b7a00ea1c13a62bb37b05b6b52a81"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "d3ce7c562cb2d457391f3ea7992f1018055544035097547d9bc2d30b7429c8ea"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "3ef916454266cdbcbd3f517c53b1e27b360caa5266bf1b44d0d627aeab643516"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "4ff75cf886bb8bef7a230f4a6f6eaf6cd23e2ad10d089f2170c4c84700dd40c7"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "a6948eb25808d55a8dc3b9a64999181ebae738c3679ced2981c7c1ec34b9b0b6"
metafile = true

[[files]]
file = "mods/suggestion-tweaker.pw.toml"
hash = "9a1695184cdb4646ae5deef3ed576e7dc1235cff1ff20493aa482a2c512928b0"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "84062fb9e90f4eb1a6321e88fd189180434d4c68ae4d7dbd3e231c1680f7dd5e"
metafile = true

[[files]]
file = "mods/techutils.pw.toml"
hash = "0249cc906fb5b69b6295e2c461016e84cfc6001ab21e949c326d9a1b9820c5af"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "0cafc885a5a30fb13bea98030be1f205ea50d1eb00ab55d2ab2bed5930b62af1"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "f9161065555655876765c7888f463038b556f3e78f8c06decba16ae8fdbaa6a8"
metafile = true

[[files]]
file = "mods/unobtainable-blocks.pw.toml"
hash = "e620c847af24c12c8fa9eeff26f2be1b8e5a5e027ff7140efd2d4f73ddc258b4"
metafile = true

[[files]]
file = "mods/viabackwards.pw.toml"
hash = "dbfff1665e3860bfae28b9422a41ef7eb855fd47a240e99e2f9c85df45eeb136"
metafile = true

[[files]]
file = "mods/viafabric.pw.toml"
hash = "b81081c495d63d9f900265deaf439b297c1a736c66803f00e1166d54f07f1dae"
metafile = true

[[files]]
file = "mods/viaversion.pw.toml"
hash = "df8d4aad8cb6e67674de68d68f5c6b216704170ef721f3abdc8d739a7b2d39d2"
metafile = true

[[files]]
file = "mods/vkm.pw.toml"
hash = "a82ae8587e822cb0a9d94cbba6d16165c7ba66666ce44ce2dfe179ae8bfe8ab3"
metafile = true

[[files]]
file = "mods/voxy.pw.toml"
hash = "61483b80dcc8a1fc130c15ca9b8971228a9c8ab0840813bcf7b4858407ec391f"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "3b769b28e94bdb53d2d5e103390844dd7693de5484d097f10d049f433e025b20"
metafile = true

[[files]]
file = "mods/worldedit-hang-fix.pw.toml"
hash = "16c5dc2e8dbf22fbe5d8bdb25566b717201d1e9ea4067d9df957912900201c14"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "a54e7a239e22265e4f6717415e730b904e5e5581f0028dfed8b06769d18fa613"
metafile = true

[[files]]
file = "mods/worldthreader.pw.toml"
hash = "e97ea47156160c65c8d4c52e8055908873bdc78b6f41a27320e08c7daeba0840"
metafile = true

[[files]]
file = "mods/yaca.pw.toml"
hash = "19c332d7ace86a2a881db91c280976b8cfc6e4dc68bae1d4859f2f2757f6c919"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "c96e6f37f930d1dde6543566d2c4f56a9a40eae2c1f75ec5b2a3cd214e0af351"
metafile = true

[[files]]
file = "mods/zfastnoise.pw.toml"
hash = "9b95250916e14512b88aac808a4ab382ba9abfee880d08b038204e08e4e35184"
metafile = true

[[files]]
file = "resourcepacks/redstone-tweaks.pw.toml"
hash = "31b53c71c2bf08da156167befe54b5717e71ee871e10ef78a70967a0bdc8b56b"
metafile = true
